[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ArduinoJson@^6.21.0
    PubSubClient@^2.8
    paulstoffregen/OneWire@^2.3.8
    DallasTemperature@^3.11.0
    DHT sensor library@^1.4.4
    claws/BH1750@^1.3.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_LOG_LEVEL=3

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.100.168
